rabbitmq:
  test:
    username: username
    password: password
    host: 192.168.56.101
    port: 5672
    virtualhost: revi.host
    routeKey: sample.route
    exchangeName: sample.exchange
    queueName: testQueue
    deadLetterExchange: dead.letter.exchange
    deadLetterRouteKey: dead.letter.route
