rabbitmq:
  test:
    username: username
    password: password
    host: localhost
    port: 5672
    virtualhost: revi.vhost
    routeKey: sample.route
    exchangeName: sample.exchange
    queueName: testQueue
    deadLetterExchange: dead.letter.exchange
    deadLetterRouteKey: dead.letter.route
